### ISSUE TITLE
Handle a limited number of reverted transactions

### ISSUE THREAD

**Issue by guidiaz** [witnet/price_feed_poller#36]
If `requestUpdate` transactions on any price feed start to revert, those updates will be retried over and over again provoking drainage of funds.

So, the poller MUST:
- account for eventual consecutive reverts on every supported price feed;
- if a threshold is reached, the poller must stop the polling workflow for the failing price feed
- after a threshold is met, however, the poller should log specific error message on every single polling period, including reference to last reverting tx hash
 
Additional notes:
- the polling workflow for a failing price feed could only be enabled again by restarting the whole poller app;
- possibly, some configuration adjustments may be required to avoid further reverts, before restarting the app.

**Comment by aesedepece** [comment]
Exponential backoff could also be useful here.

**Comment by guidiaz** [comment]
> Exponential backoff could also be useful here.

Perhaps for controlling transaction rejections (in another issue), but not reverted transactions. Reverted transactions imply something wrong in either the poller or the rpc gateway configuration that needs to be fixed asap.
